--[[ iSAC - Custom Values List 

	These are lists of default values to be used with iSAC. These values can be used, but you're not limited to and can specify your own values if you wish to do so.
	Many, if not all, of these values are taken from Sida's Auto Carry.
	
	]]--

return {
	ResetSpells = {
		Blitzcrank = "PowerFist",
		Darius = "DariusNoxianTacticsONH",
		Nidalee = "Takedown",
		Sivir = "Ricochet",
		Teemo = "BlindingDart",
		Vayne = "VayneTumble",
		Jax = "JaxEmpowerTwo",
		Mordekaiser = "MordekaiserMaceOfSpades",
		Nasus = "SiphoningStrikeNew",
		Rengar = "RengarQ",
		Wukong = "MonkeyKingDoubleAttack",
		Yorick = "YorickSpectral",
		Vi = "ViE",
		Garen = "GarenSlash3",
		Hecarim = "HecarimRamp",
		XinZhao = "XenZhaoComboTarget",
		Leona = "LeonaShieldOfDaybreak",
		Shyvana = {"ShyvanaDoubleAttack", "shyvanadoubleattackdragon"},
		Talon = "TalonNoxianDiplomacy",
		Trundle = "TrundleTrollSmash",
		Volibear = "VolibearQ",
		Poppy = "PoppyDevastatingBlow",
	},
	AASpells = {
		Ashe = "frostarrow",
		Caitlyn = "CaitlynHeadshotMissile",
		Quinn = "QuinnWEnhanced",
		Trundle = "TrundleQ",
		XinZhao = "XenZhaoThrust",
		Garen = "GarenSlash2",
		Renekton = {"RenektonExecute", "RenektonSuperExecute"},
	},
	projSpeeds = {
		Ahri         = 1.6,
		Anivia       = 1.05,
		Annie        = 1.0,
		Ashe         = 2.0,
		Brand        = 1.975,
		Caitlyn      = 2.5,
		Cassiopeia   = 1.22,
		Corki        = 2.0,
		Draven       = 1.4,
		Ezreal       = 2.0,
		FiddleSticks = 1.75,
		Graves       = 3.0,
		Heimerdinger = 1.4,
		Janna        = 1.2,
		Jayce        = 2.2,
		Karma        = 1.2,
		Karthus      = 1.25,
		Kayle        = 1.8,
		Kennen       = 1.35,
		KogMaw       = 1.8,
		Leblanc      = 1.7,
		Lulu         = 2.5,
		Lux          = 1.55,
		Malzahar     = 1.5,
		MissFortune  = 2.0,
		Morgana      = 1.6,
		Nidalee      = 1.7,
		Orianna      = 1.4,
		Quinn        = 1.85,
		Ryze         = 2.4,
		Sivir        = 1.4,
		Sona         = 1.6,
		Soraka       = 1.0,
		Swain        = 1.6,
		Syndra       = 1.2,
		Teemo        = 1.3,
		Tristana     = 2.25,
		TwistedFate  = 1.5,
		Twitch       = 2.5,
		Urgot        = 1.3,
		Vayne        = 2.0,
		Varus        = 2.0,
		Veigar       = 1.05,
		Viktor       = 2.25,
		Vladimir     = 1.4,
		Xerath       = 1.2,
		Ziggs        = 1.5,
		Zilean       = 1.25,
		Zyra         = 1.7,
	},
}

--UPDATEURL=
--HASH=BDA88218641D4BBA8EDB209941BC9CEB
